default_settings: null
behaviors:
  IARedNeuronal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 4
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        gamma: 0.85
        encoding_size: 128
        demo_path: Demos/DemosRecord_0.demo
        demo_path: Demos/DemosRecord_1.demo
        demo_path: Demos/DemosRecord_2.demo
        demo_path: Demos/DemosRecord_3.demo
        demo_path: Demos/DemosRecord_4.demo
        demo_path: Demos/DemosRecord_5.demo
        demo_path: Demos/DemosRecord_6.demo
        demo_path: Demos/DemosRecord_7.demo
        demo_path: Demos/DemosRecord_8.demo
        demo_path: Demos/DemosRecord_9.demo
        demo_path: Demos/DemosRecord_10.demo
        demo_path: Demos/DemosRecord_11.demo
        demo_path: Demos/DemosRecord_12.demo
        demo_path: Demos/DemosRecord_13.demo
        demo_path: Demos/DemosRecord_14.demo
        demo_path: Demos/DemosRecord_15.demo
        demo_path: Demos/DemosRecord_16.demo
        demo_path: Demos/DemosRecord_17.demo
        demo_path: Demos/DemosRecord_18.demo
        demo_path: Demos/DemosRecord_19.demo
        demo_path: Demos/DemosRecord_20.demo
        demo_path: Demos/DemosRecord_21.demo
        demo_path: Demos/DemosRecord_22.demo
        demo_path: Demos/DemosRecord_23.demo
        demo_path: Demos/DemosRecord_24.demo
        demo_path: Demos/DemosRecord_25.demo
        demo_path: Demos/DemosRecord_26.demo
        demo_path: Demos/DemosRecord_27.demo
        demo_path: Demos/DemosRecord_28.demo
        demo_path: Demos/DemosRecord_29.demo
        demo_path: Demos/DemosRecord_30.demo
        demo_path: Demos/DemosRecord_31.demo
        demo_path: Demos/DemosRecord_32.demo
        demo_path: Demos/DemosRecord_33.demo
        demo_path: Demos/DemosRecord_34.demo
        demo_path: Demos/DemosRecord_35.demo
        demo_path: Demos/DemosRecord_36.demo
        demo_path: Demos/DemosRecord_37.demo
        demo_path: Demos/DemosRecord_38.demo
        demo_path: Demos/DemosRecord_39.demo
        demo_path: Demos/DemosRecord_40.demo
        demo_path: Demos/DemosRecord_41.demo
        demo_path: Demos/DemosRecord_42.demo
        demo_path: Demos/DemosRecord_43.demo
        demo_path: Demos/DemosRecord_44.demo
        demo_path: Demos/DemosRecord_45.demo
        demo_path: Demos/DemosRecord_46.demo
        demo_path: Demos/DemosRecord_47.demo
        demo_path: Demos/DemosRecord_48.demo
       
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 2000
      team_change: 100000
  
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
